//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4ZsoftwareCompanyWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebsite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebsite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4ZsoftwareCompanyWebsite.Resources.ResWebsite", typeof(ResWebsite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظهور نتائج الصفحة ف نتائج البحث الاولى.
        /// </summary>
        public static string lb1st {
            get {
                return ResourceManager.GetString("lb1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسليم 200+ تطبيقات الهاتف المحمول.
        /// </summary>
        public static string lb200__Mobile_Apps_Delivered {
            get {
                return ResourceManager.GetString("lb200+ Mobile Apps Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم برنامج 4Z خدمات التسويق الرقمي الموجهة نحو الأهداف. ينصب التركيز الأساسي على مساعدة العلامات التجارية على الحصول على وجود رقمي كبير وتضخيم فرص التحويل. يضم فريقنا من محترفي التسويق الرقمي مع خبرة 11 عامًا في الصناعة. نحن نعمل مع أحدث اتجاهات التسويق الرقمي والابتكارات لضمان تطابق إطار التسويق الرقمي المخصص لإرشادات محرك البحث..
        /// </summary>
        public static string lb4 {
            get {
                return ResourceManager.GetString("lb4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدم خدمات تطوير تطبيقات الهواتف المحمولة في جميع انحاء العالم على جميع المنصات 
        ///iOS (iPhone / iPad) و Androidــ.
        /// </summary>
        public static string lb4Z_Software_provides_world_class_mobile_application_development_services_for_iOS___iPhone___iPad____Android_and_develop_cross_platform_apps_ {
            get {
                return ResourceManager.GetString("lb4Z Software provides world-class mobile application development services for iO" +
                        "S ( iPhone / iPad ), Android and develop cross-platform apps.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85٪ عملاء متكررين.
        /// </summary>
        public static string lb85 {
            get {
                return ResourceManager.GetString("lb85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إطلاق 95٪ من المشاريع.
        /// </summary>
        public static string lb95 {
            get {
                return ResourceManager.GetString("lb95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة رائدة لتطوير تطبيقات الأجهزة المحمولة منذ عام 2009 ، نقوم بتطوير التطبيقات مع أدوات وتكنولوجيا متقدمة لتلبية احتياجات المستهلكين والمؤسسات..
        /// </summary>
        public static string lbA_leading {
            get {
                return ResourceManager.GetString("lbA leading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد أهداف العمل أو استشر عاداتنا عالية الجودة والموجهة نحو الدقة
        ///                                خدمات تطوير CRM وتحسين مخرجات الأعمال وكفاءتها..
        /// </summary>
        public static string lbaddress {
            get {
                return ResourceManager.GetString("lbaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات التسويق الرقمي بأسعار معقولة.
        /// </summary>
        public static string lbAffordable_digital_marketing_services {
            get {
                return ResourceManager.GetString("lbAffordable digital marketing services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير البرامج بتقنية أجيل.
        /// </summary>
        public static string lbAgile_Development {
            get {
                return ResourceManager.GetString("lbAgile Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدم خدمات تطوير تطبيقات الهاتف المحمول متعددة المنصات من فئة 5 نجوم لتناسب المتطلبات التقنية للشركات في جميع الصناعات..
        /// </summary>
        public static string lbAll {
            get {
                return ResourceManager.GetString("lbAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لديك بالفعل برامج وتتطلب الصيانة؟ تواصل مع مهندسينا لجلسة استشارية لفهم كيف يمكن أن تساعد خدمات الدعم لدينا..
        /// </summary>
        public static string lbAlready_have {
            get {
                return ResourceManager.GetString("lbAlready have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصميم التطبيقات وتطويرها لنظام التشغيل iOS/Android/Web.
        /// </summary>
        public static string lbApp_Design {
            get {
                return ResourceManager.GetString("lbApp Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير التطبيقات.
        /// </summary>
        public static string lbApp_Development {
            get {
                return ResourceManager.GetString("lbApp Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظهر في الصفحة الأولى من Google للحصول على عبارات البحث التي تم اختيارها عبر الإعلانات المدفوعة وحملات التصنيف العضوي..
        /// </summary>
        public static string lbAppear {
            get {
                return ResourceManager.GetString("lbAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اختيار المشاريع التي تم اختيارها لتسليط الضوء على خبرتنا التكنولوجية في مساعدة العملاء على تحويل أفكارهم إلى حقيقة واقعة..
        /// </summary>
        public static string lbchosen {
            get {
                return ResourceManager.GetString("lbchosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اختيار المشاريع التي تم اختيارها لتسليط الضوء على خبرتنا التكنولوجية في مساعدة العملاء على تحويل أفكارهم إلى حقيقة واقعة..
        /// </summary>
        public static string lbChosen_handful_projects_highlighting_our_technological_expertise_in_assisting_clients_to_turn_their_ideas_into_reality_ {
            get {
                return ResourceManager.GetString("lbChosen handful projects highlighting our technological expertise in assisting c" +
                        "lients to turn their ideas into reality.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهادات العملاء.
        /// </summary>
        public static string lbClient_Testimonials {
            get {
                return ResourceManager.GetString("lbClient Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string lbClientele {
            get {
                return ResourceManager.GetString("lbClientele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة العملاء.
        /// </summary>
        public static string lbCLIENTS_SERVED {
            get {
                return ResourceManager.GetString("lbCLIENTS SERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة أهداف العمل أو التشاور مع خدمات تطوير CRM المخصصة المخصصة المخصصة للدقة وتحسين ناتج الأعمال وكفاءتها..
        /// </summary>
        public static string lbCloud_Migration_and_Support {
            get {
                return ResourceManager.GetString("lbCloud Migration and Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Platforms.
        /// </summary>
        public static string lbCMS_Platforms {
            get {
                return ResourceManager.GetString("lbCMS Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن فريق تكنولوجيا المعلومات خبره على مدار 50 عاما لاكتشاف المشكلات التقنية وتصميم خريطة طريق المنتج وتصورها وتطوير منتج يتوافق مع أهداف العمل..
        /// </summary>
        public static string lbCollaborate {
            get {
                return ResourceManager.GetString("lbCollaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمع بين العمليات التجارية الحاسمة مع خدمات تطوير البرمجيات المخصصة لتخطيط موارد المؤسسات في مصر لإدارة تدفقات العمل والقوى العاملة وعمليات التصنيع..
        /// </summary>
        public static string lbCombine {
            get {
                return ResourceManager.GetString("lbCombine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combine.
        /// </summary>
        public static string lbCombinename {
            get {
                return ResourceManager.GetString("lbCombinename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        public static string lbCONNECT_WITH_US {
            get {
                return ResourceManager.GetString("lbCONNECT WITH US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منصات الاتصال.
        /// </summary>
        public static string lbConnectivity_Platforms {
            get {
                return ResourceManager.GetString("lbConnectivity Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشاور.
        /// </summary>
        public static string lbConsultation {
            get {
                return ResourceManager.GetString("lbConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق المحتوى.
        /// </summary>
        public static string lbCONTENT_MARKETING {
            get {
                return ResourceManager.GetString("lbCONTENT MARKETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل التحويل.
        /// </summary>
        public static string lbCONVERSION_RATE {
            get {
                return ResourceManager.GetString("lbCONVERSION RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويل أفكارك إلى برامج مربحة..
        /// </summary>
        public static string lbConvert {
            get {
                return ResourceManager.GetString("lbConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات الأساسية.
        /// </summary>
        public static string lbCore_Services {
            get {
                return ResourceManager.GetString("lbCore Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستعانة بمصادر خارجية فعالة من حيث التكلفة مقابل تعيين فريق داخلي.
        /// </summary>
        public static string lbCost {
            get {
                return ResourceManager.GetString("lbCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستعانة بمصادر خارجية فعالة من حيث التكلفة مقابل توظيف الفريق الداخلي.
        /// </summary>
        public static string lbCost_effective_outsourcing_vs__in_house_team_hiring {
            get {
                return ResourceManager.GetString("lbCost-effective outsourcing vs. in-house team hiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بإنشاء معرفات صور العلامة التجارية التي تمكن المستهلكين من التعرف على الشركة والتواصل معها ، وتعزيز المبيعات والإيرادات..
        /// </summary>
        public static string lbCreate {
            get {
                return ResourceManager.GetString("lbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعرف علي فريق العمل.
        /// </summary>
        public static string lbCreative_Team {
            get {
                return ResourceManager.GetString("lbCreative Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإبداع هو شغفنا ، نجاحك هو هدفنا.
        /// </summary>
        public static string lbCreativity {
            get {
                return ResourceManager.GetString("lbCreativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة أهداف العمل أو التشاور مع خدمات تطوير CRM المخصصة المخصصة المخصصة للدقة وتحسين ناتج الأعمال وكفاءتها..
        /// </summary>
        public static string lbCRM_Platforms {
            get {
                return ResourceManager.GetString("lbCRM Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRO هو نظام يساعد في زيادة النسبة المئوية للزوار إلى موقع ويب يتحول إلى عملاء..
        /// </summary>
        public static string lbCRO {
            get {
                return ResourceManager.GetString("lbCRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات تطوير تطبيقات الهاتف المحمول المخصصة.
        /// </summary>
        public static string lbCustom_Mobile {
            get {
                return ResourceManager.GetString("lbCustom Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات تطوير البرمجيات والتطبيقات المخصصة.
        /// </summary>
        public static string lbCustom_Software_and_Application_Development_Services {
            get {
                return ResourceManager.GetString("lbCustom Software and Application Development Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير البرمجيات.
        /// </summary>
        public static string lbcustom_software_development {
            get {
                return ResourceManager.GetString("lbcustom software development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات تطوير البرمجيات المخصصة.
        /// </summary>
        public static string lbCustom_Software_Development_Services {
            get {
                return ResourceManager.GetString("lbCustom Software Development Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صممنا مئات من تطبيقات الجوال الإحترافية بأكثر من لغة ولعملاءنا المنتشرين فى دول العالم المختلفة , برمجنا العديد من المشروعات الكبرى المعتمدة على تطبيقات وأنظمة الجوال , ونسعى لتغيير واقع تطبيقات الجوال فى العالم العربي وجعلها بالفعل سهلة ومتاحة للجميع.
        /// </summary>
        public static string lbdelivers {
            get {
                return ResourceManager.GetString("lbdelivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير.
        /// </summary>
        public static string lbDevelopment {
            get {
                return ResourceManager.GetString("lbDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسويق الرقمي: امنح رحلة جديدة لعملك.
        /// </summary>
        public static string lbDigital_Marketin {
            get {
                return ResourceManager.GetString("lbDigital Marketin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسوق الشبكي.
        /// </summary>
        public static string lbDigital_Marketing_Solutions {
            get {
                return ResourceManager.GetString("lbDigital Marketing Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسويق المباشر.
        /// </summary>
        public static string lbDirect_Marketing {
            get {
                return ResourceManager.GetString("lbDirect Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتشاف، تصميم، تطوير.
        /// </summary>
        public static string lbDiscover {
            get {
                return ResourceManager.GetString("lbDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حلول تطوير التطبيقات.
        /// </summary>
        public static string lbEndpoint_App_Development_Solution {
            get {
                return ResourceManager.GetString("lbEndpoint App Development Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنجليزية.
        /// </summary>
        public static string lbEnglish {
            get {
                return ResourceManager.GetString("lbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Systems.
        /// </summary>
        public static string lbERP_Systems {
            get {
                return ResourceManager.GetString("lbERP Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حلول الجوال المميزة.
        /// </summary>
        public static string lbFeatured_Mobile_Solutions {
            get {
                return ResourceManager.GetString("lbFeatured Mobile Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاريع مميزة.
        /// </summary>
        public static string lbFeatured_Projects {
            get {
                return ResourceManager.GetString("lbFeatured Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string lbFrench {
            get {
                return ResourceManager.GetString("lbFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتساب الجر الاجتماعي لمنتج/خدمة العلامة التجارية مع نسخة إبداعية وإعلانات مدفوعة على منصات التواصل الاجتماعي..
        /// </summary>
        public static string lbGain {
            get {
                return ResourceManager.GetString("lbGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احصل على عرض أسعار مجاني.
        /// </summary>
        public static string lbGet_A_Free_Quote {
            get {
                return ResourceManager.GetString("lbGet A Free Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابقى على تواصل.
        /// </summary>
        public static string lbGet_In_Touch {
            get {
                return ResourceManager.GetString("lbGet In Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البدء.
        /// </summary>
        public static string lbGET_STARTED {
            get {
                return ResourceManager.GetString("lbGET STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لمحة عن المشاريع.
        /// </summary>
        public static string lbGlimpse_of_Projects {
            get {
                return ResourceManager.GetString("lbGlimpse of Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكامل الأجهزة.
        /// </summary>
        public static string lbHardware_Integration {
            get {
                return ResourceManager.GetString("lbHardware Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مميزات خدمات التسويق الرقمي لدينا؟.
        /// </summary>
        public static string lbHow {
            get {
                return ResourceManager.GetString("lbHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصناعة التي نخدمها.
        /// </summary>
        public static string lbIndustry_We_Serve {
            get {
                return ResourceManager.GetString("lbIndustry We Serve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اندماج.
        /// </summary>
        public static string lbIntegration {
            get {
                return ResourceManager.GetString("lbIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هو سوق للخدمات حيث يقوم العملاء بنشر متطلباتهم والمهنية
        ///                                        البحث عن وظائف. مهمات الاستعانة بمصادر خارجية ، مهام الاستعانة بمصادر خارجية ، المساعدة في التوصيل ، المساعدين الشخصيين ، الشخصيين
        ///                                        بواب ومساعد شخصي.
        /// </summary>
        public static string lbIntegrity {
            get {
                return ResourceManager.GetString("lbIntegrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أشخاص أذكياء ومتحمسون يؤمنون بإنشاء حلول تقنية متقدمة على مستوى المؤسسة وبأسعار معقولة للشركات الناشئة وشركات Fortune 500..
        /// </summary>
        public static string lbIntelligent {
            get {
                return ResourceManager.GetString("lbIntelligent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إطار اللغات.
        /// </summary>
        public static string lbLanguages_Framework {
            get {
                return ResourceManager.GetString("lbLanguages Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا &amp; ابدأ.
        /// </summary>
        public static string lbLet {
            get {
                return ResourceManager.GetString("lbLet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من العملاء المتوقعين = المزيد من المبيعات = المزيد من الإيرادات: هذه هي خدمات التسويق الرقمي من
        ///(4Z Software)  
        ///، باختصار. نحن وكالة تسويق رقمية تعتمد على البيانات والتي تعتمد على الأداء وتساعد العلامة التجارية على الحصول على رؤية الويب وتحسين التحويلات والوعي بالعلامة التجارية..
        /// </summary>
        public static string lblong {
            get {
                return ResourceManager.GetString("lblong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال صيانة.
        /// </summary>
        public static string lbMaintenance {
            get {
                return ResourceManager.GetString("lbMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصيانة والدعم.
        /// </summary>
        public static string lbMaintenance_and_Support {
            get {
                return ResourceManager.GetString("lbMaintenance and Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعرف على برنامج شركة لخدمات التسويق الرقمي القائمة على البيانات.
        /// </summary>
        public static string lbMeet_Your {
            get {
                return ResourceManager.GetString("lbMeet Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترحيل أصول الأعمال الرقمية إلى بيئة الحوسبة السحابية وحماية مع جدار الحماية. تحقيق التحول الرقمي وفتح فرص النمو..
        /// </summary>
        public static string lbMigrate {
            get {
                return ResourceManager.GetString("lbMigrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير تطبيقات الهاتف المحمول.
        /// </summary>
        public static string lbMobile_App_Development {
            get {
                return ResourceManager.GetString("lbMobile App Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات تطبيقات الهاتف المحمول.
        /// </summary>
        public static string lbMobile_Application_Services {
            get {
                return ResourceManager.GetString("lbMobile Application Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد من العملاء المتوقعين = المزيد من المبيعات = المزيد من الإيرادات: هذه هي خدمات التسويق الرقمي من
        ///                                        4Z Software ، باختصار. نحن وكالة تسويق رقمية تعتمد على البيانات والأداء
        ///                                        يساعد العلامة التجارية في الحصول على رؤية على شبكة الإنترنت ، وتحسين التحويلات والوعي بالعلامة التجارية..
        /// </summary>
        public static string lbMoree {
            get {
                return ResourceManager.GetString("lbMoree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقدم برنامج 4Z خدمات تطوير برامج مخصصة في مصر لكل من أغراض B2C و B2B..
        /// </summary>
        public static string lboffers {
            get {
                return ResourceManager.GetString("lboffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلامات التجارية عبر الإنترنت.
        /// </summary>
        public static string lbOnline_Branding {
            get {
                return ResourceManager.GetString("lbOnline Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقوم مهندسو تطوير CMS لدينا بتصميم ودمج أطر عمل المحتوى مع
        ///                                هيكل الأعمال لبناء عملية سير عمل مبسطة..
        /// </summary>
        public static string lbOur {
            get {
                return ResourceManager.GetString("lbOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهدافنا.
        /// </summary>
        public static string lbOur_Approach {
            get {
                return ResourceManager.GetString("lbOur Approach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات التسويق لدينا.
        /// </summary>
        public static string lbOur_Marketing_Services {
            get {
                return ResourceManager.GetString("lbOur Marketing Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمكن حلولنا الشركات الناشئة والمؤسسات من التوسع.
        /// </summary>
        public static string lbOur_Solutions_Enable_Startups_And_Enterprises_To_Scale {
            get {
                return ResourceManager.GetString("lbOur Solutions Enable Startups And Enterprises To Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتكون فريقنا من العديد من المطورين المتخصصين في لغات البرمجة المختلفة..
        /// </summary>
        public static string lbOur_team {
            get {
                return ResourceManager.GetString("lbOur team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يعكس عملنا جودتنا وموثوقيتنا وإدراكنا لأحدث التقنيات..
        /// </summary>
        public static string lbOur_work_reflects {
            get {
                return ResourceManager.GetString("lbOur work reflects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبيقات من اعمالنا.
        /// </summary>
        public static string lbOur_Work_Showcase {
            get {
                return ResourceManager.GetString("lbOur Work Showcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقوم بخدمات تطوير موقع الويب المخصصة لدينا ببناء أدوات رقمية فعالة ومبتكرة لشركتك وعملائك وعملائك لحل تحديات الأعمال وتحويل العمليات التجارية.
        ///نحن نقدم خدمات تطوير مواقع الويب المخصصة ببناء وتصميم و تطوير الويب بجودة عالية للعملاء في جميع انواع المجالات.
        /// </summary>
        public static string lbOurcustom {
            get {
                return ResourceManager.GetString("lbOurcustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حملات التوعية لجمهور تمت تصفيته ، عضويا ومباشرًا ، يبحثون عن المنتج/الخدمة التي توفرها الشركة..
        /// </summary>
        public static string lbOutreach {
            get {
                return ResourceManager.GetString("lbOutreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحركه الأداء والموجهة نحو البيانات مع تقارير قابلة للقياس.
        /// </summary>
        public static string lbPerformance {
            get {
                return ResourceManager.GetString("lbPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Rate.
        /// </summary>
        public static string lbPlateRate {
            get {
                return ResourceManager.GetString("lbPlateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateRate هو تطبيق رائع لمساعدتك في العثور على الطعام الذي تحبه أينما كنت! PlateRate تساعدك في العثور عليها
        ///                                        طعام أفضل ، من خلال مراجعات عناصر القائمة وتتبع التفضيلات الغذائية. يجمع PlateRate بين الطعام و
        ///                                        مراجعة المشروبات وتقييمها مع إمكانية البحث بناءً على تفضيلاتك الغذائية وتطابق النكهة..
        /// </summary>
        public static string lbPlateRate_is {
            get {
                return ResourceManager.GetString("lbPlateRate is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software 4Z 
        ///هو مزود لخدمات تطوير البرمجيات المخصصة في مصر ، حيث يقوم المهندسون بالتوسع والمرونة منتجات برمجيات للويب والهاتف المحمول. تتضمن خدمات تطوير البرمجيات والتطبيقات المخصصة لدينا تسليم برامج دورة كاملة ، من التفكير إلى الدعم المستمر بعد التسليم..
        /// </summary>
        public static string lbprovider {
            get {
                return ResourceManager.GetString("lbprovider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضع محتوى مفهومين (SEO والمحتوى) تم إنشاؤه بهدف حركة مرور محرك البحث الساحر..
        /// </summary>
        public static string lbPutting {
            get {
                return ResourceManager.GetString("lbPutting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسليم حركة المرور المؤهلة والمستهدفة ؛ لا حركة روبوت.
        /// </summary>
        public static string lbQualified {
            get {
                return ResourceManager.GetString("lbQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسليم حركة المرور المؤهلة والمستهدفة ؛ لا حركة روبوت.
        /// </summary>
        public static string lbQualified_and_targeted_traffic_delivered__no_bot_traffic {
            get {
                return ResourceManager.GetString("lbQualified and targeted traffic delivered; no bot traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير التطبيقات React Native.
        /// </summary>
        public static string lbReact_Native_App_Development {
            get {
                return ResourceManager.GetString("lbReact Native App Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكرار العملاء.
        /// </summary>
        public static string lbREPEAT_CUSTOMERS {
            get {
                return ResourceManager.GetString("lbREPEAT CUSTOMERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مباشرة من السلكية إلى النماذج الأولية ل MVP ، يبني فريقنا من المبرمجين حلولًا مبتكره بالصناعة مع تجربة سلسة متعددة الأجهزة. احصل على أفضل تقنية متنقلة لعملك..
        /// </summary>
        public static string lbRight {
            get {
                return ResourceManager.GetString("lbRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Optimization_(SEO).
        /// </summary>
        public static string lbSe {
            get {
                return ResourceManager.GetString("lbSe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحسين محرك البحث (SEO).
        /// </summary>
        public static string lbSearch {
            get {
                return ResourceManager.GetString("lbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحسين محرك البحث والتسويق.
        /// </summary>
        public static string lbSearch_Engine_Optimization___Marketing {
            get {
                return ResourceManager.GetString("lbSearch Engine Optimization & Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string lbSERVICES {
            get {
                return ResourceManager.GetString("lbSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق وسائل الاعلام الاجتماعية.
        /// </summary>
        public static string lbSocial_Media_Marketing {
            get {
                return ResourceManager.GetString("lbSocial Media Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق وسائل التواصل الاجتماعي (SMM).
        /// </summary>
        public static string lbSocial_Media_Marketing__SMM_ {
            get {
                return ResourceManager.GetString("lbSocial Media Marketing (SMM)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعدة متخصصة في استعادة ترتيب موقعك على الويب..
        /// </summary>
        public static string lbSpecialized {
            get {
                return ResourceManager.GetString("lbSpecialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المساعدة المتخصصة في استرداد موقع الويب الخاص بك..
        /// </summary>
        public static string lbSpecialized_assistance_in_recovering_your_website_ranking_ {
            get {
                return ResourceManager.GetString("lbSpecialized assistance in recovering your website ranking.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريك تطوير البرمجيات في شركة.
        /// </summary>
        public static string lbStartup {
            get {
                return ResourceManager.GetString("lbStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استشارات للشركات الناشئة.
        /// </summary>
        public static string lbStartup_Consulting {
            get {
                return ResourceManager.GetString("lbStartup Consulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستشارات الاستراتيجية.
        /// </summary>
        public static string lbStrategic_Consulting {
            get {
                return ResourceManager.GetString("lbStrategic Consulting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهدف من ذلك هو توليد حركة مرور مستهدفة إلى موقع الويب وإنشاء محادثة إيجابية حول علامتك التجارية..
        /// </summary>
        public static string lbThe {
            get {
                return ResourceManager.GetString("lbThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يعمل فريق من المهندسين مع العملاء لمعالجة البيانات الموجودة في أدوات الأجهزة المتخصصة ، والمساعدة في  رفع الأداء ، وكفاءة النظام ، والنسخ الاحتياطي ، والاسترداد ، وازدواج الوسائط ، ودعمها وصيانتها..
        /// </summary>
        public static string lbThe_hardware {
            get {
                return ResourceManager.GetString("lbThe hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوات والتقنيات.
        /// </summary>
        public static string lbTools___Technologies {
            get {
                return ResourceManager.GetString("lbTools & Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل شركة متخصصة لتطوير تطبيقات الويب والهاتف المحمول.
        /// </summary>
        public static string lbTOP_CUSTOM_WEB_AND_MOBILE_APP_DEVELOPMENT_COMPANY {
            get {
                return ResourceManager.GetString("lbTOP CUSTOM WEB AND MOBILE APP DEVELOPMENT COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل وكالة التسويق الرقمي في مصر.
        /// </summary>
        public static string lbTop_Digital {
            get {
                return ResourceManager.GetString("lbTop Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من افضل شركات تطوير تطبيقات الهواتف في مصر.
        /// </summary>
        public static string lbTop_Mobile {
            get {
                return ResourceManager.GetString("lbTop Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثق بنا لإعطاء التزام 100 ٪ بنجاح علامتك التجارية..
        /// </summary>
        public static string lbTrust_us_to_give_100__commitment_to_the_success_of_your_brand_ {
            get {
                return ResourceManager.GetString("lbTrust us to give 100% commitment to the success of your brand.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصميم UI/UX.
        /// </summary>
        public static string lbUI {
            get {
                return ResourceManager.GetString("lbUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استخدم خدمات تطوير البرامج والتطبيقات المخصصة لإنشاء منصات مجتمعية موجهة للمستخدمين أو منصات الشبكات الاجتماعية بسهولة..
        /// </summary>
        public static string lbUse {
            get {
                return ResourceManager.GetString("lbUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديو له قيمة ضخمة عبر الإنترنت. من خلال المقاطع العائمة ، يمكنك إظهار منتجاتك وخدماتك بطريقة أكثر قابلية للتقدم.
        /// </summary>
        public static string lbVideo {
            get {
                return ResourceManager.GetString("lbVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق الفيديو.
        /// </summary>
        public static string lbVIDEO_MARKETING {
            get {
                return ResourceManager.GetString("lbVIDEO MARKETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atchOut توفير واجهة مع جميع وظائف التتبع وزر مساعدة الطوارئ
        ///                                        في حالة حدوث حالة ذعر أثناء السفر في السيارة. خفض معدل الجريمة
        ///                                        داخل المدينة والحصول على المساعدة المناسبة حتى لو كان الاتصال ضعيفًا في المنطقة التي يوجد بها
        ///                                        حدثت مشكلة..
        /// </summary>
        public static string lbWatchOut {
            get {
                return ResourceManager.GetString("lbWatchOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن وكالة تسويق رقمية كاملة الخدمات ؛ من تحسين تصنيف محرك البحث إلى تحليل التحويل ، يتعامل فريق التسويق الرقمي الخبير لدينا جميعًا. ابحث عن أخصائي التسويق الرقمي بين فريقنا اليوم!.
        /// </summary>
        public static string lbWe_are_a_full_service_digital_marketing_agency__from_improving_search_engine_ranking_to_conversion_analysis__our_expert_digital_marketing_team_handles_all__Find_your_digital_marketing_specialist_among_our_team_today_ {
            get {
                return ResourceManager.GetString("lbWe are a full-service digital marketing agency; from improving search engine ra" +
                        "nking to conversion analysis, our expert digital marketing team handles all. Fin" +
                        "d your digital marketing specialist among our team today!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن شركة رائدة في تقديم خدمات الاستشارات التقنية لبدء التشغيل للشركات الناشئة الممولة. تجعلنا الحلول التقنية الرائدة في إنترنت الأشياء ، والذكاء الاصطناعي ، وتحليل البيانات ، والخبرة في مجالات صناعية متعددة ، شريكًا استشاريًا موثوقًا لبدء التشغيل..
        /// </summary>
        public static string lbWe_are_a_leading {
            get {
                return ResourceManager.GetString("lbWe are a leading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نصنع المنتجات.
        /// </summary>
        public static string lbWe_Build_Products {
            get {
                return ResourceManager.GetString("lbWe Build Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نساعد الشركات على بناء قدرات تقنية جديدة ، وتحسين علاقات المستخدمين ، ودخول أسواق عالمية جديدة من خلال خدمات تطوير تطبيقات iOS للجوال المخصصة في مصر. يقوم مطورو iOS الذين تم فحصهم بإنشاء تعليمات برمجية نظيفة وقابلة للتطوير داخل الشركة وتوفير الصيانة والدعم الشخصيين..
        /// </summary>
        public static string lbWe_companies {
            get {
                return ResourceManager.GetString("lbWe companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقوم بإنشاء تجارب رقمية قوية وجميلة وسلسة وقابلة للتطوير مع مصممي الويب المحترفين لدينا. يبني حل التصميم الخاص بنا الثقة والثقة في صورة علامتك التجارية وقيمتك ويميزك عن المنافسين.
        /// </summary>
        public static string lbWe_create_powerful {
            get {
                return ResourceManager.GetString("lbWe create powerful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد قمنا بتطوير تطبيقات الويب لمتطلبات الأعمال المخصصة.
        /// </summary>
        public static string lbWe_have {
            get {
                return ResourceManager.GetString("lbWe have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نساعد الشركات على القدرة على بناء تقنيات جديدة ، ودخول أسواق عالمية جديدة من خلال خدمات تطوير
        ///تطبيقات الهواتف المحموله بال React Native.
        /// </summary>
        public static string lbWe_help_companies {
            get {
                return ResourceManager.GetString("lbWe help companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعتمد على الأخلاق المرنة والمرنة لمواصلة دعم العلامات التجارية بعد الإطلاق من خلال ترقيات المنتجات وحلول التسويق الرقمي..
        /// </summary>
        public static string lbWe_rely {
            get {
                return ResourceManager.GetString("lbWe rely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن ندعم.
        /// </summary>
        public static string lbWe_Support {
            get {
                return ResourceManager.GetString("lbWe Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن نغير العلامات التجارية.
        /// </summary>
        public static string lbWe_Transform_Brands {
            get {
                return ResourceManager.GetString("lbWe Transform Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن وكالة تسويق رقمية متكاملة الخدمات ؛ من تحسين ترتيب محرك البحث إلى
        ///                                        تحليل التحويل ، يتولى فريق التسويق الرقمي الخبير لدينا كل شيء. ابحث عن رقمك الرقمي
        ///                                        أخصائي تسويق بين فريقنا اليوم!.
        /// </summary>
        public static string lbweare {
            get {
                return ResourceManager.GetString("lbweare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تدقيق الموقع.
        /// </summary>
        public static string lbWEBSITE_AUDIT {
            get {
                return ResourceManager.GetString("lbWEBSITE AUDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصميم الموقع.
        /// </summary>
        public static string lbWebsite_Design {
            get {
                return ResourceManager.GetString("lbWebsite Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطوير مواقع الويب.
        /// </summary>
        public static string lbWebsite_Development {
            get {
                return ResourceManager.GetString("lbWebsite Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما الذي نقوم به.
        /// </summary>
        public static string lbWhat_We_Do {
            get {
                return ResourceManager.GetString("lbWhat We Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمالنا.
        /// </summary>
        public static string lbWhat_We_ve_Done {
            get {
                return ResourceManager.GetString("lbWhat We\'ve Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لماذا أخترتنا.
        /// </summary>
        public static string lbWhy_Choose_Us {
            get {
                return ResourceManager.GetString("lbWhy Choose Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        public static string lbWORK_HOURS {
            get {
                return ResourceManager.GetString("lbWORK HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنوات من الخبرة.
        /// </summary>
        public static string lbYEARS_OF_EXPERIENCE {
            get {
                return ResourceManager.GetString("lbYEARS OF EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تتحد معرفتك التجارية وفطنتنا التكنولوجية مع المنهجيات المثبتة لتحويل أفكار العمل إلى كود جميل..
        /// </summary>
        public static string lbYour_business_knowledge {
            get {
                return ResourceManager.GetString("lbYour business knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريكك الموثوق به والمبتكر في تطوير المنتجات الرقمية من الدرجة الأولى..
        /// </summary>
        public static string lbYour_trusted {
            get {
                return ResourceManager.GetString("lbYour trusted", resourceCulture);
            }
        }
    }
}
